# Tema 4 - Metode de clasificare

Folositi 4 seturi de date pentru probleme de clasificare, plecand de la repository-urile specificate in Cursul 6. Cel putin un set de date sa fie cu valori lipsa; pentru un alt set de date care are initial toate valorile, introduceti dvs. in mod artificial valori lipsa, suprascriind un anumit procent din valorile initiale (ex. `p=5%`, `p` parametru) cu `numpy.nan`. 

In [111]:
import numpy as np
import pandas as pd
import sklearn

print('At the moment the program was made:')
print('\tNumPy Version = 1.20.2')
print('\tScykit_learn Version = 0.24.1')
print('\tPandas Version = 1.2.3\n')

print(f'Current NumPy Version = {np.__version__}')
print(f'Current Sklearn Version = {sklearn.__version__}')
print(f'Current Pandas Version = {pd.__version__}')

At the moment the program was made:
	NumPy Version = 1.20.2
	Scykit_learn Version = 0.24.1
	Pandas Version = 1.2.3

Current NumPy Version = 1.20.2
Current Sklearn Version = 0.24.1
Current Pandas Version = 1.2.4


1. Aplicati o metoda de missing value imputation, unde este cazul; documentati metoda folosita.
*Resurse*: Pentru missing value imputation, puteti urmari [Imputation of missing values](https://scikit-learn.org/stable/modules/impute.html), [How to Handle Missing Data with Python](https://machinelearningmastery.com/handle-missing-data-python/), [fancyimpute](https://github.com/iskandr/fancyimpute), [missingpy](https://github.com/epsilon-machine/missingpy).

* Setul de date `Planning Relax`

In [112]:
pd_data = pd.read_csv("data/planning_relax_data_set.txt", delimiter="\t", header=None)
pd_data = pd_data.drop(13, axis=1)
pd_data.head()

0        1         2         3         4        5         6   \
0 -0.17936 -0.20700 -0.209710 -0.097260 -0.119210 -0.17322 -0.280760   
1 -0.14659 -0.16494  0.249870 -0.073985  0.494940 -0.15633 -0.288910   
2 -0.13131  0.51816  0.432810  0.397890  0.043127  0.56320 -0.013246   
3  0.64940  0.41878  0.148350  0.333490 -0.219740  0.39891  0.590650   
4 -0.40628  0.11503  0.073336  0.070066 -0.030920  0.15205 -0.191420   

         7         8         9         10        11   12  
0  0.223170  0.418660 -0.032886  0.003383 -0.334250  1.0  
1  0.500800 -0.045553  0.050759 -0.017511  0.066959  1.0  
2 -0.062833 -0.883390 -0.040303  0.088057  0.631200  2.0  
3  0.077100 -1.107200 -0.367230  0.364680  0.571720  1.0  
4 -0.580430 -0.102250  0.153750 -0.126950  0.184570  1.0

In [113]:
pd_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 182 entries, 0 to 181
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       182 non-null    float64
 1   1       182 non-null    float64
 2   2       182 non-null    float64
 3   3       182 non-null    float64
 4   4       182 non-null    float64
 5   5       182 non-null    float64
 6   6       182 non-null    float64
 7   7       182 non-null    float64
 8   8       182 non-null    float64
 9   9       182 non-null    float64
 10  10      182 non-null    float64
 11  11      182 non-null    float64
 12  12      182 non-null    float64
dtypes: float64(13)
memory usage: 18.6 KB


In [114]:
pd_data = pd_data.values
pd_data_original = pd_data.copy()
assert not np.isnan(pd_data_original.sum()) # verificam ca nu e niciun nan 

Setul initial de date nu are valori lipsa, dar am implementat o functie care sa suprascrie un anumit procent din valorile initiale (dat ca parametru) folosind `numpy.nan`

In [115]:
def insert_nan(data, percentage=15):
    numbers_to_be_modified = int(percentage / 100 * data.shape[0] * data.shape[1])
    random_lines = np.random.choice(data.shape[0], numbers_to_be_modified)
    random_cols = np.random.choice(data.shape[1], numbers_to_be_modified)
    data[random_lines, random_cols] = np.nan
    return data

pd_data = insert_nan(pd_data)
print(f'DataSet after adding Nan: \n {pd_data}')
assert np.isnan(pd_data.sum()) # verificam ca e cel putin un nan

DataSet after adding Nan: 
 [[-0.17936          nan -0.20971   ...  0.0033827 -0.33425    1.       ]
 [-0.14659          nan        nan ... -0.017511   0.066959   1.       ]
 [       nan  0.51816    0.43281   ...  0.088057   0.6312     2.       ]
 ...
 [ 0.29877   -0.17962    0.032859  ...  0.24683          nan  2.       ]
 [-0.37812   -0.52287          nan ...  0.007591   0.47603          nan]
 [ 0.37913   -0.046562         nan ...  0.17369          nan  2.       ]]


In [116]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer 
# from sklearn.ensemble import ExtraTreesRegressor
imputer = IterativeImputer(max_iter=1000, random_state=0)
pd_data_sklearn = imputer.fit_transform(pd_data)
print(f'DataSet after missing values imputation: \n {pd_data_sklearn}')

DataSet after missing values imputation: 
 [[-0.17936    -0.10036008 -0.20971    ...  0.0033827  -0.33425
   1.        ]
 [-0.14659    -0.18227824  0.2776674  ... -0.017511    0.066959
   1.        ]
 [-0.18978401  0.51816     0.43281    ...  0.088057    0.6312
   2.        ]
 ...
 [ 0.29877    -0.17962     0.032859   ...  0.24683    -0.37394219
   2.        ]
 [-0.37812    -0.52287     0.22249187 ...  0.007591    0.47603
   1.29663838]
 [ 0.37913    -0.046562   -0.11213411 ...  0.17369     0.2892582
   2.        ]]


In [117]:
np.linalg.norm(pd_data_sklearn - pd_data_original)

2.7537477942095876

* Setul de date `Conventional Social Media Movies`

In [118]:
data = pd.read_excel('data/2014 and 2015 CSM dataset.xlsx', index_col=None, header=None)
data = data.drop(0, axis=0)
data = data.drop(0, axis=1)

In [119]:
data.head()

1    2  3          4          5     6  7  8        9      10   11    12  \
1  2014  6.3  8       9130    4000000    45  1  0  3280543   4632  425   636   
2  2014  7.1  1  192000000   50000000  3306  2  2   583289   3465   61   186   
3  2014  6.2  1   30700000   28000000  2872  1  0   304861    328   34    47   
4  2014  6.3  1  106000000  110000000  3470  2  0   452917   2429  132   590   
5  2014  4.7  8   17300000    3500000  2310  2  0  3145573  12163  610  1082   

         13  
1   1120000  
2  12350000  
3    483000  
4    568000  
5   1923800

In [120]:
data = data.values
print(data)
data_original = data.copy()
assert np.isnan(data.sum()) # verificam ca e cel putin un nan

[[2014 6.3 8 ... 425 636 1120000]
 [2014 7.1 1 ... 61 186 12350000]
 [2014 6.2 1 ... 34 47 483000]
 ...
 [2015 5.4 8 ... 325 409 nan]
 [2015 5.4 1 ... 67 201 nan]
 [2015 4.4 15 ... 431 606 nan]]


In [121]:
!pip install missingpy

In [122]:
import sys
import sklearn.neighbors._base
sys.modules['sklearn.neighbors.base'] = sklearn.neighbors._base

In [123]:
from missingpy import MissForest

imputer = MissForest()
data = imputer.fit_transform(data)
assert not np.isnan(data.sum()) # verificam ca nu exista niciun nan

Iteration: 0
Iteration: 1
Iteration: 2
Iteration: 3
Iteration: 4


In [124]:
print(f'Data original:\n {data_original}')
print(f'\nData filled:\n {data}')

Data original:
 [[2014 6.3 8 ... 425 636 1120000]
 [2014 7.1 1 ... 61 186 12350000]
 [2014 6.2 1 ... 34 47 483000]
 ...
 [2015 5.4 8 ... 325 409 nan]
 [2015 5.4 1 ... 67 201 nan]
 [2015 4.4 15 ... 431 606 nan]]

Data filled:
 [[2.01400000e+03 6.30000000e+00 8.00000000e+00 ... 4.25000000e+02
  6.36000000e+02 1.12000000e+06]
 [2.01400000e+03 7.10000000e+00 1.00000000e+00 ... 6.10000000e+01
  1.86000000e+02 1.23500000e+07]
 [2.01400000e+03 6.20000000e+00 1.00000000e+00 ... 3.40000000e+01
  4.70000000e+01 4.83000000e+05]
 ...
 [2.01500000e+03 5.40000000e+00 8.00000000e+00 ... 3.25000000e+02
  4.09000000e+02 2.19932847e+06]
 [2.01500000e+03 5.40000000e+00 1.00000000e+00 ... 6.70000000e+01
  2.01000000e+02 7.79592690e+05]
 [2.01500000e+03 4.40000000e+00 1.50000000e+01 ... 4.31000000e+02
  6.06000000e+02 1.71773896e+06]]


2. Pentru fiecare set de date aplicati 5 modele de clasificare din scikit learn. Pentru fiecare raportati: acuratete, precision, recall, scorul F1 - a se vedea [sklearn.metrics](http://scikit-learn.org/stable/modules/classes.html#module-sklearn.metrics), [Precision and recall](https://en.wikipedia.org/wiki/Precision_and_recall) - folosind 5 fold cross validation. Raportati mediile rezultatelor atat pentru fold-urile de antrenare, cat si pentru cele de testare. Rularile se vor face cu valori fixate ale hiperparametrilor. 

* Setul de date `Planning Relax`

In [125]:
pr_data = pd.read_csv("data/planning_relax_data_set.txt", delimiter="\t", header=None)
pr_data = pr_data.drop(13, axis=1)
pr_data.head()

0        1         2         3         4        5         6   \
0 -0.17936 -0.20700 -0.209710 -0.097260 -0.119210 -0.17322 -0.280760   
1 -0.14659 -0.16494  0.249870 -0.073985  0.494940 -0.15633 -0.288910   
2 -0.13131  0.51816  0.432810  0.397890  0.043127  0.56320 -0.013246   
3  0.64940  0.41878  0.148350  0.333490 -0.219740  0.39891  0.590650   
4 -0.40628  0.11503  0.073336  0.070066 -0.030920  0.15205 -0.191420   

         7         8         9         10        11   12  
0  0.223170  0.418660 -0.032886  0.003383 -0.334250  1.0  
1  0.500800 -0.045553  0.050759 -0.017511  0.066959  1.0  
2 -0.062833 -0.883390 -0.040303  0.088057  0.631200  2.0  
3  0.077100 -1.107200 -0.367230  0.364680  0.571720  1.0  
4 -0.580430 -0.102250  0.153750 -0.126950  0.184570  1.0

In [126]:
pr_X = pr_data.iloc[:, :-1].values
pr_y = pr_data.iloc[:, -1].values

In [127]:
print(pr_X)
print(pr_y)

[[-0.17936   -0.207     -0.20971   ... -0.032886   0.0033827 -0.33425  ]
 [-0.14659   -0.16494    0.24987   ...  0.050759  -0.017511   0.066959 ]
 [-0.13131    0.51816    0.43281   ... -0.040303   0.088057   0.6312   ]
 ...
 [ 0.29877   -0.17962    0.032859  ... -0.41113    0.24683   -0.38916  ]
 [-0.37812   -0.52287    0.21541   ... -0.039117   0.007591   0.47603  ]
 [ 0.37913   -0.046562  -0.12336   ... -0.24229    0.17369    0.49063  ]]
[1. 1. 2. 1. 1. 1. 2. 1. 1. 1. 2. 1. 1. 1. 2. 1. 1. 1. 2. 1. 1. 1. 2. 1.
 1. 1. 2. 1. 1. 1. 2. 1. 1. 1. 2. 1. 1. 1. 2. 1. 1. 1. 2. 1. 1. 1. 2. 1.
 1. 1. 2. 1. 1. 1. 2. 1. 1. 1. 2. 1. 1. 1. 2. 1. 1. 1. 2. 1. 1. 1. 2. 1.
 1. 1. 2. 1. 1. 1. 2. 1. 1. 1. 2. 1. 1. 1. 2. 1. 1. 1. 2. 1. 1. 1. 2. 1.
 1. 1. 2. 1. 1. 1. 2. 1. 1. 1. 2. 1. 1. 1. 2. 1. 1. 1. 2. 1. 1. 1. 2. 1.
 1. 1. 2. 1. 1. 1. 2. 1. 1. 1. 2. 1. 1. 1. 2. 1. 1. 1. 2. 1. 1. 1. 2. 1.
 1. 1. 2. 1. 1. 1. 2. 1. 1. 1. 2. 1. 1. 2. 1. 2. 1. 2. 1. 2. 1. 2. 1. 2.
 1. 2. 1. 2. 1. 2. 1. 2. 1. 2. 1. 2. 1. 2.]


In [128]:
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn import metrics

def our_function_micro(model, X, y):
    scores = cross_val_score(model, X, y, cv=10, scoring='accuracy')
    print(f'Accuracy: {scores.mean()}')
    
    scores = cross_val_score(model, X, y, cv=10, scoring='precision')
    print(f'Precision: {scores.mean()}')

    scores = cross_val_score(model, X, y, cv=10, scoring='recall')
    print(f'Recall: {scores.mean()}')

    scores = cross_val_score(model, X, y, cv=10, scoring='f1')
    print(f'F!_Score: {scores.mean()}')

* Folosind KNeighborsClassifier

In [129]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors=3)
our_function_micro(model=model, X=pr_X, y=pr_y)

Accuracy: 0.6213450292397661
Precision: 0.7025580267685532
Recall: 0.8076923076923077
F!_Score: 0.7477115253324931


* Folosind DecisionTreeClassifier

In [130]:
from sklearn.tree import DecisionTreeClassifier

classifier = DecisionTreeClassifier()
our_function_micro(model=classifier, X=pr_X, y=pr_y)

Accuracy: 0.5599415204678364
Precision: 0.683118548118548
Recall: 0.6846153846153846
F!_Score: 0.6921474299480296


* Folosind SupportVectorMachines

In [131]:
from sklearn.svm import SVC

classifier = SVC(kernel='linear')
our_function_micro(model=classifier, X=pr_X, y=pr_y)

Accuracy: 0.7146198830409357
Precision: 0.7146198830409357
Recall: 1.0
F!_Score: 0.8334677419354838


* Folosind SochasticGradientDescent

In [132]:
from sklearn.linear_model import SGDClassifier

classifier=SGDClassifier(loss='hinge', penalty='l2')
our_function_micro(model=classifier, X=pr_X, y=pr_y)

Accuracy: 0.5830409356725147
Precision: 0.7286138139466314
Recall: 0.6615384615384616
F!_Score: 0.7360069918957571


* Folosind RBF

In [133]:
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF

kernel = 1.0 * RBF(1.0)
gpc = GaussianProcessClassifier(kernel=kernel)
our_function_micro(model=gpc, X=pr_X, y=pr_y)

Accuracy: 0.7146198830409357
Precision: 0.7146198830409357
Recall: 1.0
F!_Score: 0.8334677419354838


* Setul de date `Divorce`


In [134]:
divorce_data = pd.read_excel('data/divorce.xlsx', index_col=None, header=None)
divorce_data = divorce_data.drop(0, axis=0)

In [135]:
# divorce_data.head()
print(divorce_data)

    0  1  2  3  4  5  6  7  8  9   ... 45 46 47 48 49 50 51 52 53 54
1    2  2  4  1  0  0  0  0  0  0  ...  2  1  3  3  3  2  3  2  1  1
2    4  4  4  4  4  0  0  4  4  4  ...  2  2  3  4  4  4  4  2  2  1
3    2  2  2  2  1  3  2  1  1  2  ...  3  2  3  1  1  1  2  2  2  1
4    3  2  3  2  3  3  3  3  3  3  ...  2  2  3  3  3  3  2  2  2  1
5    2  2  1  1  1  1  0  0  0  0  ...  2  1  2  3  2  2  2  1  0  1
..  .. .. .. .. .. .. .. .. .. ..  ... .. .. .. .. .. .. .. .. .. ..
166  0  0  0  0  0  0  0  0  0  0  ...  1  0  4  1  1  4  2  2  2  0
167  0  0  0  0  0  0  0  0  0  0  ...  4  1  2  2  2  2  3  2  2  0
168  1  1  0  0  0  0  0  0  0  1  ...  3  0  2  0  1  1  3  0  0  0
169  0  0  0  0  0  0  0  0  0  0  ...  3  3  2  2  3  2  4  3  1  0
170  0  0  0  0  0  0  0  1  0  0  ...  3  4  4  0  1  3  3  3  1  0

[170 rows x 55 columns]


In [136]:
divorce_X = divorce_data.iloc[:, :-1].values
divorce_y = divorce_data.iloc[:, -1].values
divorce_y = divorce_y.astype('int')

* Folosind KNeighborsClassifier

In [138]:
#from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors=3)
our_function_micro(model=model, X=divorce_X, y=divorce_y)

Accuracy: 0.9764705882352942
Precision: 1.0
Recall: 0.9555555555555555
F!_Score: 0.9741176470588236


* Folosind DecisionTreeClassifier

In [139]:
classifier = DecisionTreeClassifier()
our_function_micro(model=classifier, X=divorce_X, y=divorce_y)

Accuracy: 0.9588235294117649
Precision: 0.968888888888889
Recall: 0.9666666666666666
F!_Score: 0.968888888888889


* Folosind SupportVectorMachines

In [140]:
classifier = SVC(kernel='linear')
our_function_micro(model=classifier, X=divorce_X, y=divorce_y)

Accuracy: 0.9823529411764707
Precision: 1.0
Recall: 0.9666666666666666
F!_Score: 0.9800000000000001


* Folosind SochasticGradientDescent

In [141]:
classifier=SGDClassifier(loss='hinge', penalty='l2')
our_function_micro(model=classifier, X=divorce_X, y=divorce_y)

Accuracy: 0.9705882352941178
Precision: 0.9777777777777779
Recall: 0.9555555555555555
F!_Score: 0.9571241830065359


* Folosind RBF

In [142]:
kernel = 1.0 * RBF(1.0)
gpc = GaussianProcessClassifier(kernel=kernel)
our_function_micro(model=gpc, X=divorce_X, y=divorce_y)

Accuracy: 0.9823529411764707
Precision: 1.0
Recall: 0.9666666666666666
F!_Score: 0.9800000000000001


* Setul de date `HCV`

In [143]:
data_HCV = pd.read_csv('data/hcv_data.csv')
data_HCV = data_HCV.drop('Unnamed: 0', axis=1)
data_HCV.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 615 entries, 0 to 614
Data columns (total 13 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Category  615 non-null    object 
 1   Age       615 non-null    int64  
 2   Sex       615 non-null    object 
 3   ALB       614 non-null    float64
 4   ALP       597 non-null    float64
 5   ALT       614 non-null    float64
 6   AST       615 non-null    float64
 7   BIL       615 non-null    float64
 8   CHE       615 non-null    float64
 9   CHOL      605 non-null    float64
 10  CREA      615 non-null    float64
 11  GGT       615 non-null    float64
 12  PROT      614 non-null    float64
dtypes: float64(10), int64(1), object(2)
memory usage: 62.6+ KB


In [144]:
from sklearn.preprocessing import LabelEncoder

labelencoder = LabelEncoder()

data_HCV.Category = data_HCV.Category.astype('category')
data_HCV.Category = data_HCV.Category.cat.codes
data_HCV.Sex = data_HCV.Sex.astype('category')
data_HCV.Sex = data_HCV.Sex.cat.codes
data_HCV.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 615 entries, 0 to 614
Data columns (total 13 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Category  615 non-null    int8   
 1   Age       615 non-null    int64  
 2   Sex       615 non-null    int8   
 3   ALB       614 non-null    float64
 4   ALP       597 non-null    float64
 5   ALT       614 non-null    float64
 6   AST       615 non-null    float64
 7   BIL       615 non-null    float64
 8   CHE       615 non-null    float64
 9   CHOL      605 non-null    float64
 10  CREA      615 non-null    float64
 11  GGT       615 non-null    float64
 12  PROT      614 non-null    float64
dtypes: float64(10), int64(1), int8(2)
memory usage: 54.2 KB


In [145]:
data_HCV = data_HCV.fillna(data_HCV.mean())
data_HCV.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 615 entries, 0 to 614
Data columns (total 13 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Category  615 non-null    int8   
 1   Age       615 non-null    int64  
 2   Sex       615 non-null    int8   
 3   ALB       615 non-null    float64
 4   ALP       615 non-null    float64
 5   ALT       615 non-null    float64
 6   AST       615 non-null    float64
 7   BIL       615 non-null    float64
 8   CHE       615 non-null    float64
 9   CHOL      615 non-null    float64
 10  CREA      615 non-null    float64
 11  GGT       615 non-null    float64
 12  PROT      615 non-null    float64
dtypes: float64(10), int64(1), int8(2)
memory usage: 54.2 KB


In [146]:
HCV_X = data_HCV.iloc[:, 1:].values
HCV_y = data_HCV.iloc[:, 0].values

In [148]:
np.any(np.isnan(data_HCV))

False

In [149]:
import warnings
import sklearn.exceptions
warnings.filterwarnings("ignore", category=sklearn.exceptions.UndefinedMetricWarning)

In [150]:
def our_function_macro(model, X, y):
    scores = cross_val_score(model, X, y, cv=7, scoring='accuracy')
    print(f'Accuracy: {scores.mean()}')
    
    scores = cross_val_score(model, X, y, cv=7, scoring='precision_macro')
    print(f'Precision: {scores.mean()}')

    scores = cross_val_score(model, X, y, cv=7, scoring='recall_macro')
    print(f'Recall: {scores.mean()}')

    scores = cross_val_score(model, X, y, cv=7, scoring='f1_macro')
    print(f'F1_Score: {scores.mean()}')

* Folosind KNeighborsClassifier

In [151]:
model = KNeighborsClassifier(n_neighbors=3)
our_function_macro(model=model, X=HCV_X, y=HCV_y)

Accuracy: 0.908922973578146
Precision: 0.5280122107497461
Recall: 0.4322055137844611
F1_Score: 0.4570349274056598


* Folosind DecisionTreeClassifier

In [152]:
classifier = DecisionTreeClassifier()
our_function_macro(model=classifier, X=HCV_X, y=HCV_y)

Accuracy: 0.8991640543364682
Precision: 0.5852963257873434
Recall: 0.5328467272076295
F1_Score: 0.4595072183424836


* Folosind SupportVectorMachines

In [153]:
classifier = SVC(kernel='linear')
our_function_macro(model=classifier, X=divorce_X, y=divorce_y)

Accuracy: 0.9771428571428571
Precision: 0.9831932773109244
Recall: 0.9761904761904762
F1_Score: 0.9761904761904762


* Folosind SochasticGradientDescent

In [154]:
classifier=SGDClassifier(loss='hinge', penalty='l2')
our_function_macro(model=classifier, X=divorce_X, y=divorce_y)

Accuracy: 0.9711904761904762
Precision: 0.9811126373626374
Recall: 0.9720695970695971
F1_Score: 0.9764440228865159


* Folosind RBF

In [155]:
kernel = 1.0 * RBF(1.0)
gpc = GaussianProcessClassifier(kernel=kernel)
our_function_macro(model=gpc, X=divorce_X, y=divorce_y)

Accuracy: 0.9771428571428571
Precision: 0.9831932773109244
Recall: 0.9761904761904762
F1_Score: 0.9761904761904762


* Setul de date `Conventional Social Media Movies`

In [156]:
CSM_data = pd.read_excel('data/2014 and 2015 CSM dataset.xlsx', index_col=None, header=None)
CSM_data = CSM_data.drop(0, axis=0)
CSM_data = CSM_data.drop(0, axis=1)

In [157]:
CSM_data.head()

1    2  3          4          5     6  7  8        9      10   11    12  \
1  2014  6.3  8       9130    4000000    45  1  0  3280543   4632  425   636   
2  2014  7.1  1  192000000   50000000  3306  2  2   583289   3465   61   186   
3  2014  6.2  1   30700000   28000000  2872  1  0   304861    328   34    47   
4  2014  6.3  1  106000000  110000000  3470  2  0   452917   2429  132   590   
5  2014  4.7  8   17300000    3500000  2310  2  0  3145573  12163  610  1082   

         13  
1   1120000  
2  12350000  
3    483000  
4    568000  
5   1923800

In [158]:
from missingpy import MissForest

imputer = MissForest()
CSM_data = imputer.fit_transform(CSM_data)
assert not np.isnan(CSM_data.sum()) # verificam ca nu exista niciun nan

Iteration: 0
Iteration: 1
Iteration: 2
Iteration: 3


In [159]:
CSM_y = CSM_data[:, 2]
CSM_X = CSM_data[:, [0, 1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]]

In [161]:
from sklearn.model_selection import ShuffleSplit
def our_function_macro(model, X, y):
    cv = ShuffleSplit(n_splits=10, test_size=1/3, random_state=0)
    scores = cross_val_score(model, X, y, cv=cv, scoring='accuracy')
    print(f'Accuracy: {scores.mean()}')
    
    scores = cross_val_score(model, X, y, cv=cv, scoring='precision_weighted')
    print(f'Precision: {scores.mean()}')

    scores = cross_val_score(model, X, y, cv=cv, scoring='recall_weighted')
    print(f'Recall: {scores.mean()}')

    scores = cross_val_score(model, X, y, cv=cv, scoring='f1_weighted')
    print(f'F1_Score: {scores.mean()}')

* Folosind KNeighborsClassifier

In [162]:
model = KNeighborsClassifier(n_neighbors=5)
our_function_macro(model=model, X=CSM_X, y=CSM_y)

Accuracy: 0.2987012987012987
Precision: 0.24873059931626568
Recall: 0.2987012987012987
F1_Score: 0.25872185418450416


* Folosind DecisionTreeClassifier

In [163]:
classifier = DecisionTreeClassifier()
our_function_macro(model=classifier, X=CSM_X, y=CSM_y)

Accuracy: 0.27662337662337666
Precision: 0.281505104086133
Recall: 0.26623376623376627
F1_Score: 0.2531397924806694


* Folosind SupportVectorMachines

In [164]:
classifier = SVC()
our_function_macro(model=classifier, X=CSM_X, y=CSM_y)

Accuracy: 0.3467532467532468
Precision: 0.22525110839934542
Recall: 0.3467532467532468
F1_Score: 0.25272170102599734


* Folosind SochasticGradientDescent

In [165]:
classifier=SGDClassifier(loss='hinge', penalty='l2')
our_function_macro(model=classifier, X=CSM_X, y=CSM_y)

Accuracy: 0.1896103896103896
Precision: 0.18949641969207137
Recall: 0.2012987012987013
F1_Score: 0.16054788579517865


* Folosind RBF

In [166]:
kernel = 1.0 * RBF(1.0)
gpc = GaussianProcessClassifier(kernel=kernel)
our_function_macro(model=gpc, X=CSM_X, y=CSM_y)

Accuracy: 0.03766233766233766
Precision: 0.0015685613088210492
Recall: 0.03766233766233766
F1_Score: 0.0029998456066172444


3. Raportati performanta fiecarui model, folosind 5 fold cross validation. Pentru fiecare din cele 5 rulari, cautati hiperparametrii optimi folosind 4-fold cross validation. Performanta modelului va fi raportata ca medie a celor  5 rulari. 
    
    *Observatie:* la fiecare din cele 5 rulari, hiperparametrii optimi pot diferi, din cauza datelor utilizate pentru antrenare/validare. 

* Setul de date `Planning Relax`

* Folosind KNeighborsClassifier

In [167]:
pr_data = pd.read_csv("data/planning_relax_data_set.txt", delimiter="\t", header=None)
pr_data = pr_data.drop(13, axis=1)
pr_X = pr_data.iloc[:, :-1].values
pr_y = pr_data.iloc[:, -1].values

In [168]:
from sklearn.model_selection import cross_validate, cross_val_score
from sklearn.metrics import accuracy_score

medii = []

for _ in range(5):
    best_score = 0
    for k in range(1, 31):
        for p in [1, 2, 3, 10]:
            model = KNeighborsClassifier(n_neighbors=k, p=p)
            score = np.mean(cross_val_score(model, pr_X, pr_y, cv=10))
            if score >= best_score:
                best_score = score
                best_params = {'n_neighbors':k, 'p':p}

    print('\nIteration ', _)
    print('\tBest score:', best_score)
    print('\tBest params:', best_params)  

    model = KNeighborsClassifier(**best_params)
    model.fit(pr_X, pr_y)
    y_predicted = model.predict(pr_X)
    print('\tAccuracy on whole set:', accuracy_score(pr_y, y_predicted))
    medii += [accuracy_score(pr_y, y_predicted)]

print(f'Media acuratetei dupa 5 iteratii este: {np.mean(medii)}')


Iteration  0
	Best score: 0.725438596491228
	Best params: {'n_neighbors': 2, 'p': 3}
	Accuracy on whole set: 0.8021978021978022

Iteration  1
	Best score: 0.725438596491228
	Best params: {'n_neighbors': 2, 'p': 3}
	Accuracy on whole set: 0.8021978021978022

Iteration  2
	Best score: 0.725438596491228
	Best params: {'n_neighbors': 2, 'p': 3}
	Accuracy on whole set: 0.8021978021978022

Iteration  3
	Best score: 0.725438596491228
	Best params: {'n_neighbors': 2, 'p': 3}
	Accuracy on whole set: 0.8021978021978022

Iteration  4
	Best score: 0.725438596491228
	Best params: {'n_neighbors': 2, 'p': 3}
	Accuracy on whole set: 0.8021978021978022
Media acuratetei dupa 5 iteratii este: 0.8021978021978022
